sonar.organization=shwetankvashishtha
sonar.projectKey=ShwetankVashishtha_ai-sandbox

sonar.sources=pages,utilities,playwright.config.ts
sonar.tests=tests

sonar.exclusions=\
  node_modules/**,\
  playwright-report/**,\
  test-results/**,\
  coverage/**,\
  data/**,\
  .git/**,\
  .github/**,\
  .vscode/**,\
  .sonarlint/**

sonar.test.inclusions=tests/**/*.ts

sonar.sourceEncoding=UTF-8